// Milestone burn-up (OPS-0009).
//
//   node scripts/ops/burnup.mjs [--write]
//
// Points: S = 1, M = 3, L = 8. For each phase, total scope and completed points are sampled from the
// roadmap files at the last commit of every ISO week in git history (plus the working tree today).
// Forecast finish = today + remaining points / mean weekly velocity over the last 4 weeks (all history
// if shorter). A forecast more than 14 days past the phase's gate date (docs/production/gates.json)
// is flagged "SCOPE REVIEW" — the weekly status note must then open a scope review (OPS-0026).
// --write regenerates docs/production/burnup.md.
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseTasks, PHASES, POINTS, readRoadmap } from './roadmap.mjs';

const ROOT = resolve(fileURLToPath(new URL('../..', import.meta.url)));
const git = (...a) => execFileSync('git', a, { cwd: ROOT, encoding: 'utf8', maxBuffer: 64 << 20 });
const DAY = 86400000;

export function points(tasks) {
  const out = Object.fromEntries(PHASES.map((p) => [p, { total: 0, done: 0 }]));
  for (const t of tasks) {
    out[t.phase].total += POINTS[t.size];
    if (t.done) out[t.phase].done += POINTS[t.size];
  }
  return out;
}

/** Forecast date for one phase from weekly samples [{date, done, total}] (sorted). */
export function forecast(samples, today = new Date()) {
  const last = samples[samples.length - 1];
  const window = samples.slice(-5);
  const weeks = window.length > 1 ? (new Date(window[window.length - 1].date) - new Date(window[0].date)) / (7 * DAY) : 0;
  const velocity = weeks > 0 ? (window[window.length - 1].done - window[0].done) / Math.max(1, weeks) : 0;
  const remaining = last.total - last.done;
  if (remaining <= 0) return { velocity, date: today, remaining: 0 };
  if (velocity <= 0) return { velocity, date: null, remaining };
  return { velocity, remaining, date: new Date(today.getTime() + (remaining / velocity) * 7 * DAY) };
}

function weeklySamples() {
  const log = git('log', '--format=%H %cI', '--', 'docs/roadmap').trim().split('\n').filter(Boolean);
  const byWeek = new Map();
  for (const line of log) {
    const [sha, iso] = line.split(' ');
    const d = new Date(iso);
    const monday = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate() - ((d.getUTCDay() + 6) % 7)));
    const key = monday.toISOString().slice(0, 10);
    if (!byWeek.has(key)) byWeek.set(key, sha); // log is newest-first: first hit is the week's last commit
  }
  const samples = [];
  for (const [week, sha] of [...byWeek].sort()) {
    const files = git('ls-tree', '--name-only', sha, 'docs/roadmap/').split('\n').filter((f) => /\/0\d-.*\.md$/.test(f));
    const tasks = files.flatMap((f) => parseTasks(git('show', `${sha}:${f}`), f));
    samples.push({ date: week, pts: points(tasks) });
  }
  samples.push({ date: new Date().toISOString().slice(0, 10), pts: points(readRoadmap(ROOT)) });
  return samples;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const gates = JSON.parse(readFileSync(join(ROOT, 'docs/production/gates.json'), 'utf8'));
  const samples = weeklySamples();
  const today = new Date();
  let md = `# Milestone burn-up\n\nGenerated by \`node scripts/ops/burnup.mjs --write\` on ${today.toISOString().slice(0, 10)} — do not edit by hand. Points: S = 1, M = 3, L = 8.\n\n`;
  md += `| Phase | Scope (pts) | Done (pts) | Done % | Velocity (pts/wk, last 4 wk) | Forecast finish | Gate | Status |\n|---|---:|---:|---:|---:|---|---|---|\n`;
  for (const p of PHASES) {
    const series = samples.map((s) => ({ date: s.date, ...s.pts[p] }));
    const last = series[series.length - 1];
    const f = forecast(series, today);
    const gate = gates[p]?.date;
    const late = gate && (!f.date || f.date - new Date(gate) > 14 * DAY);
    const status = f.remaining === 0 ? 'complete' : late ? '**SCOPE REVIEW**' : gate ? 'on track' : '—';
    md += `| ${p} | ${last.total} | ${last.done} | ${last.total ? Math.round((100 * last.done) / last.total) : 0}% | ${f.velocity.toFixed(1)} | ${f.date ? f.date.toISOString().slice(0, 10) : 'no velocity yet'} | ${gate ?? '—'} | ${status} |\n`;
  }
  md += `\n## Weekly samples (done / scope points)\n\n| Week of | ${PHASES.join(' | ')} |\n|---|${PHASES.map(() => '---:').join('|')}|\n`;
  for (const s of samples) md += `| ${s.date} | ${PHASES.map((p) => `${s.pts[p].done} / ${s.pts[p].total}`).join(' | ')} |\n`;
  md += `\nA phase flagged **SCOPE REVIEW** (forecast > 14 days past its gate, or no velocity) must be raised in the next weekly status note (docs/production/status/) and handled under change control (docs/production/change-control.md).\n`;
  if (process.argv.includes('--write')) writeFileSync(join(ROOT, 'docs/production/burnup.md'), md);
  console.log(md);
}
