// Cross-workstream dependency map (OPS-0011).
//
//   node scripts/ops/deps.mjs [--write]
//
// Lists every roadmap task whose text names another workstream (ENG, PLT, INP, UIX, AUD, QAT, LOC, OPS,
// GAM, BOS, NAR, CON, ART) — the task's owner prefix and the depended-on prefix are the two owners — and
// a prefix × prefix matrix. --write regenerates docs/production/dependencies-generated.md.
// Phase conflicts need judgement and are curated by hand in docs/production/dependencies.md.
import { writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readRoadmap } from './roadmap.mjs';

const ROOT = resolve(fileURLToPath(new URL('../..', import.meta.url)));
const PREFIXES = ['ENG', 'PLT', 'INP', 'UIX', 'AUD', 'QAT', 'LOC', 'OPS', 'GAM', 'BOS', 'NAR', 'CON', 'ART'];

export function dependencies(tasks) {
  const out = [];
  for (const t of tasks) {
    const named = new Set([...t.text.matchAll(/\b([A-Z]{3})\b/g)].map((m) => m[1]).filter((p) => PREFIXES.includes(p) && p !== t.prefix));
    for (const p of named) out.push({ id: t.id, phase: t.phase, from: t.prefix, to: p, title: t.title });
  }
  return out;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const deps = dependencies(readRoadmap(ROOT));
  const used = PREFIXES.filter((p) => deps.some((d) => d.from === p || d.to === p));
  let md = `# Cross-workstream dependencies (generated)\n\nGenerated by \`node scripts/ops/deps.mjs --write\` — do not edit. ${deps.length} task → workstream dependencies. Curated phase conflicts and resolutions: [dependencies.md](dependencies.md).\n\n## Matrix (rows depend on columns)\n\n| from \\ to | ${used.join(' | ')} |\n|---|${used.map(() => '---:').join('|')}|\n`;
  for (const f of used) md += `| **${f}** | ${used.map((t) => deps.filter((d) => d.from === f && d.to === t).length || '').join(' | ')} |\n`;
  md += `\n## Dependencies by task\n\n| Task | Phase | Owner | Depends on | Title |\n|---|---|---|---|---|\n`;
  for (const d of deps) md += `| ${d.id} | ${d.phase} | ${d.from} | ${d.to} | ${d.title.replace(/\|/g, '\\|')} |\n`;
  if (process.argv.includes('--write')) writeFileSync(join(ROOT, 'docs/production/dependencies-generated.md'), md);
  console.log(`${deps.length} dependencies across ${used.length} workstreams`);
}
