/**
 * Case notes for Chapters III–V (NAR-0170): the day-book pages after each late operation, in the
 * same template as the demo's — patient, presenting complaint, procedure, an outcome per rank band
 * and one personal line. Each variant stays under 120 words.
 */
import type { CaseNote } from './casenotes';

const note = (op: string, patient: string, presenting: string, procedure: string, high: string, mid: string, low: string, observation: string): CaseNote => ({
  op,
  patient,
  presenting,
  procedure,
  outcome: { high, mid, low },
  observation,
});

export const CASE_NOTES_LATER: readonly CaseNote[] = [
  note('op3-1', 'Liesl, a founder’s daughter, seven.', 'Two horn-buds through the scalp, each over a Choir sigil.', 'Cut the bone discs, lifted them, excised or dressed the buds as the certificate stood. Salved the scalp.', 'Clean discs and a scalp that will hardly mark. She asked if my hands were gentle; I hope they were.', 'Buds dealt with, scalp closed. A little heat at the bone; she will mend.', 'Done roughly, the bone overheated once. She lives, and will wear a cap a while.', 'Her mother held her hand throughout. I wrote the certificate before I washed.'),
  note('op3-2', 'Kaspar, powder-mill guard.', 'Lead ball through the thigh, carrying doublet cloth; heavy bleeding after the blast.', 'Opened the track, drew the ball, found every scrap of wadding under the lens, took two splinters, closed.', 'Every scrap found, no fever. He will walk the gate in a month.', 'Ball and cloth out, closed sound. He will limp until spring.', 'A scrap nearly stayed in; the fever came and went. He lives, and keeps the leg.', 'His good doublet is now mostly in a dish.'),
  note('op3-4', 'Three powder-mill hands — Jannik, Old Rudi, Wenzel.', 'Blast wounds on three at once: burns, shrapnel, a torn artery.', 'Worked the three tables in turn on one clock, the artery first, then the burns, then the iron.', 'All three walked out. Ilse wrote it in the ledger twice to be sure.', 'All three saved; Rudi will lose a finger to it.', 'We kept all three, just. Wenzel will carry the scars of the day.', 'They will not go back to the mill. I do not blame them.'),
  note('op3-3', 'Ute Brandt, bell-founder.', 'Cramping colic, grey veins in the gut under the lens: lead from the furnaces.', 'Chelating tincture on each deposit, drew off the grey bile with the leech-pipe.', 'Every deposit dissolved. She will cast again, and should wear a cloth over her mouth.', 'Most of the lead gone; the colic eases. She will be back.', 'Some lead stays. She lives, and will mend slowly on milk and rest.', 'The Guild calls it a trade complaint. I call it poison with a pension.'),
  note('op3-5', 'Berthold, carter.', 'A carrion crow’s beak broken off beside the eye.', 'Drew the beak along its own line with the tongs; cleaned and closed the socket-edge.', 'The eye is saved and clear. He drove home that afternoon.', 'Beak out, eye saved, some bruising. He will squint a week.', 'The eye is bruised badly but he keeps it. He will mend.', 'He wants the beak mounted. Ilse has refused on the hospice’s behalf.'),
  note('op3-6', 'Frieda, laundress.', 'A worm in the gut from bad pie, regrowing what was cut.', 'Cut it segment by segment from the tail, branding each stump before it could regrow.', 'Taken whole in segments, nothing left to regrow. She is angrier at the pieman than at me.', 'The worm is out; one segment regrew once. She will mend.', 'A long fight with a patient worm. She lives, and will keep off pies.', 'The pieman has sent a pie by way of apology. Nobody will eat it.'),
  note('op3-7', 'Mother Agathe, elf, of the Grey Beguines.', 'Buboes of the Kilnrows plague, in an elder who has nursed it sixty years.', 'Lanced each bubo across the crown, drained, salved.', 'Every bubo lanced clean. She was back in the Rows by evening, scolding.', 'Drained and dressed. She rested a day, under protest.', 'Rough lancing, one festered. She lives, and nursed herself, which she prefers.', 'She blessed my hands and then told me how to hold them.'),
  note('op3-8', 'Brother Ansgar, penitent.', 'A scourged back gone bad under the ash rubbed into it.', 'Cleaned the wounds, drained the pus, salved and closed the worst.', 'Clean and closed. He will scourge himself again; I have made it harder.', 'Cleaned and dressed. He asked for it to hurt, and it did not.', 'Some wounds stay open. He lives, and will carry them in procession.', 'He thanked me for nothing. I think he meant it kindly.'),
  note('op3-9', 'Inquisitor Stroh, Ash Tribunal.', 'An abscess over a rotten lower molar; a great many questions.', 'Lanced and drained the abscess, rocked and drew the molar, salved the socket.', 'The tooth came whole, root and all. He said “hm”, which I understand is Haller’s word.', 'Tooth out, a little of the root left for the socket to push out. He will mend.', 'The root broke; I had to go after it. He lives, and keeps a grudge.', 'He asked about the names and the child. I answered with the tongs.'),
  note('op3-10', 'Oswin Tallert, Registrar of Kessendorf.', 'The plague dead writing themselves across his skin: Prime.', 'Opened along the ink, unwrote the names newest-first, branded the quill, mended the cuts.', 'The roll is closed and the skin clean. He is copying the roll again from memory.', 'The quill is gone; some names left faint scars. He will mend.', 'Many names cut deep before they were struck. He lives, and keeps the ledger.', 'Some of the names were my patients. Prime knew them.'),
  note('op3-11', 'Master Haller, guild surgeon.', 'Hexfire in three organs, then burns to the bone in both hands: Terce.', 'Salved the fronts, cut the roots, took off the eschar, salved and stitched the hands.', 'His hands will close on a pen, and very nearly a lancet.', 'The fire is out. The hands are scarred; he will not operate again.', 'We kept him, not the hands. He lives, and will shout by letter.', 'He told me to work faster the whole time. He was right.'),
  note('op4-1', 'Ushkar Split-Tusk, orc crossbowman.', 'A company quarrel at the gorget, beside the artery.', 'Clamped the artery with the tongs, drew the bolt, stitched the hide with slow strokes.', 'Clean through hide like a saddle. He kept the quarrel for luck.', 'Out and closed; the hide made the stitching slow. He will mend.', 'The lancet skated twice. He lives, and did not complain once.', 'Ostrau pays him double. I would pay him triple not to be shot again.'),
  note('op4-10', 'Jorgen, pikeman, and his cot-mate.', 'Two men on two cots, one surgeon.', 'Worked both tables on one clock, the worse first, switching between them.', 'Both men saved and both on their feet within the week.', 'Both saved, though Jorgen waited longer than I liked.', 'We kept them both, barely. Jorgen will carry his mate’s gratitude, loudly.', 'He asked me to see to the other man first. I did.'),
  note('op4-2', 'Wendel, convoy guard.', 'A boar’s tusk wound and a mule’s hoof, one morning.', 'Drained the mud, cleaned and stitched the tusk wound, salved the hoof bruise.', 'Clean and closed. He guarded the convoy from the wagon the next day.', 'Closed sound; the bruise will take weeks.', 'The mud nearly festered. He lives, and will keep off mules.', 'He is making the tusk into a dagger. The boar would approve.'),
  note('op4-3', 'Brakka, of Orsa Flintvein’s crew.', 'Delver’s lung: crystal nodules hardening in the chest.', 'Cracked the early nodules with the lancet, branded and cracked the late ones; never touched the beard.', 'Every nodule out. He breathes like a boy and owes me a knot.', 'Most nodules out; a late one needed the brand twice. He will mend.', 'Some nodules stay. He lives, and will keep off the deep seams a season.', 'Orsa tied a knot in his beard for me. I am told it is an honour.'),
  note('op4-4', 'Gutram, giant of the Ostrau company.', 'A pay-chest swallowed whole, its lock still working.', 'Opened, turned the three pins against the gut’s rhythm, drew the chest, closed.', 'Chest out with the lock intact. The clerk counted every coin.', 'Chest out; one pin slipped and cost time. He will mend.', 'A long wrestle with the lock. He lives, and keeps his pay.', 'He swears he did not swallow it on purpose. Nobody believes him.'),
  note('op4-5', 'Lord Eckbert von Salm, patron of the Ostrau company.', 'Cold, grey, one heartbeat a minute; fang fragments in the neck.', 'Pulled every fragment under the lens, restarted the heart with the tincture on the beat, closed the bite.', 'The trance broke on the first beat. He woke asking for his horse.', 'The heart took on the second try. He will mend.', 'Many missed beats before it took. He lives, and keeps his patronage.', 'Stroh wanted a verdict. I gave him a breathing man instead.'),
  note('op4-6', 'Margit, camp-follower.', 'The same bite over and over on one side of the neck; a bond.', 'Pulled the tooth fragments, closed the bites, and branded or salved the channel as was decided.', 'Clean work. Whatever was chosen, it was done well.', 'Bites closed; the channel dealt with. She will mend.', 'Rough work on a tender neck. She lives, and keeps her choice.', 'She asked me to listen before I cut. It is not often asked.'),
  note('op4-8', 'Hanne, sutler’s daughter.', 'Stone spreading from the fingertips at her wedding.', 'Halted the front with the tincture, cracked each plate free with the tongs, salved beneath.', 'Every plate off, the hand moves. She went back to the altar that evening.', 'Most of the hand saved; two fingers stiff. She will mend.', 'The stone spread twice behind me. She lives, and will carry a stiff hand.', 'The groom waited. I am told he wept, which the Watch will not forget.'),
  note('op4-7', 'Captain Mauer, Kessendorf Watch.', 'Stone crusting over the organs while the vitals read calm: Sext.', 'Opened, chipped the crust away, branded beneath, took the tincture when my hands slowed, tended and closed.', 'He sat up and counted his men. Thirty-five.', 'The stone is gone; he is weak. He will mend and march.', 'Much of it maimed him. He lives, and will keep his post from a chair.', 'The calm on the monitor was the worst of it. It lied well.'),
  note('op4-9', 'Pieter, militiaman.', 'A burrower from an old arrow wound, tunnelling for the heart: None.', 'Found the head with the lens, cut across it, branded it, tended the tunnels.', 'Taken well short of the heart. He wants to go back on the line.', 'Taken close to the heart; the tunnels will ache. He will mend.', 'It reached the heart’s wall. He lives, and keeps the tunnel-scars.', 'His old arrow wound was mine to close in the spring. I closed it again.'),
  note('op5-5', 'Sergeant Lotte Harrach, Kessendorf Watch.', 'Hexstone shot from the procession, whispering in the wound.', 'Branded the stones still, carried each straight to the lead dish, closed.', 'Every stone in the dish. She went back to the Penny Stair.', 'Stones out, one whispered longer than I liked. She will mend.', 'A stone nearly took her thoughts. She lives, and keeps her post.', 'The lead dish hummed all night. Ilse covered it with a cloth.'),
  note('op5-1', 'Jakob, cathedral chorister.', 'Extra vocal folds in the throat, humming the procession’s hymn.', 'Cut the folds away in the silences between verses; closed.', 'His own voice back, clear. He sang a street song to prove it.', 'His voice back, a little hoarse. He will mend.', 'Long work in short silences. He lives, and keeps a rasp.', 'Emmerich knew the hymn. I wish he did not.'),
  note('op5-2', 'Dietmar, tanner.', 'A talking cyst in the belly that knows my secrets.', 'Cut all the way round it, clear of the wall; lifted it whole; closed the bed.', 'Whole and silent in the dish. He slept that night.', 'Out whole, a nick in the wall. He will mend.', 'It nearly burst. He lives, and keeps well away from the dish.', 'It said things about the candles. I did not listen, but I heard.'),
  note('op5-3', 'Greta, chandler’s daughter.', 'Blood thickening to tallow in the vessels.', 'Softened the clots with the salve, drew them off with the leech-pipe before they set.', 'Every clot drawn. Her blood runs; her father’s candles light.', 'Most drawn; a clot set once. She will mend.', 'The tallow set more than once. She lives, and will carry a pallor.', 'Vespers was practising on her. I am glad it failed.'),
  note('op5-4', 'Rosina, labouring mother.', 'A labour on Hollow Night, with something in the room that wanted the child.', 'Worked for two patients on one table until both were safe.', 'Mother and daughter both well. The girl is named after the Sister.', 'Both saved; the mother will be weak a while.', 'A hard night. Both live; the mother will mend slowly.', 'Ilse held the child first. She did not say anything for a long time.'),
  note('op5-6', 'Sister Ilse, of the Merciful Order.', 'Wick-filaments in the vessels, blood to tallow, the ward’s lamps dying with her: Vespers.', 'Kept the lamps lit, cut the wicks in their light, softened and drew off the tallow, tidied her.', 'Every lamp lit, every wick cut. She woke and asked about the ledger.', 'The lamps held, just. She will mend.', 'Two lamps went out. She lives, and keeps the ledger with a shaking hand.', 'She wanted to go with it. I would not let her.'),
  note('op5-7', 'Guard-captain Ebner, the Burgomaster’s guard.', 'Sewn through with every Hour so far: ink, fire and a burrower.', 'Took the echoes in the order Orsa called them — Prime, Terce, None — then mended.', 'Each echo taken in turn. He pointed us below.', 'All three taken; the fire took longest. He will mend.', 'A long fight with three Hours. He lives, and carries all three scars.', 'He was a message. The Precentor wanted me to read it.'),
  note('op5-8', 'The host of Compline: Inquisitor Stroh, or the Burgomaster.', 'Compline sung into him; his heart slowing to a perfect end; the Litany stolen.', 'Took each mask as it came, broke the silence-nodes for the Litany, opened the core with lancet and brand together.', 'The silence broke clean. He woke loud and complaining.', 'The silence broke late. He will mend.', 'A near thing at the last. He lives, and keeps the quiet in his eyes.', 'He smiled all the way down. I did not let him arrive.'),
  note('op5-9', 'Aurel Vennholt, the Precentor.', 'The whole Office burned into him: eight sigils, the unisons, the heart.', 'Unsang each Hour in its manner, then the pairs, then the heart. Kept him alive throughout.', 'The Office unsung, and the patient whole. He asked what waking was for.', 'Unsung, with damage. He will mend in a cell.', 'The heart nearly went with the Office. He lives, and will carry it.', 'Haller struck him off for mercy. I kept him for the same reason.'),
];
