// Builds docs/ROADMAP.md from docs/roadmap/0*.md: validates task lines and tabulates progress.
// Usage: node scripts/roadmap-index.mjs
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';

const dir = 'docs/roadmap';
const files = readdirSync(dir).filter((f) => /^0\d-.*\.md$/.test(f)).sort();
const TASK = /^- \[([ x])\] ([A-Z]{3})-(\d{4}) · (M0|Demo|Alpha|Beta|Release|Post) · (P[0-3]) · ([SML]) · (.+)$/;
const PHASES = ['M0', 'Demo', 'Alpha', 'Beta', 'Release', 'Post'];
const PREFIX_NAME = {
  ENG: 'Engine & rendering', PLT: 'Platform, build & systems', INP: 'Input & controls', UIX: 'UI/UX, HUD & accessibility',
  AUD: 'Audio', QAT: 'QA, testing & tooling', LOC: 'Localisation', OPS: 'Production, legal & release',
  GAM: 'Core surgery gameplay', BOS: 'Malison bosses', NAR: 'Narrative & writing', CON: 'Content production', ART: 'Art & visual direction',
};
const tasks = [];
const bad = [];
const ids = new Set();
for (const f of files) {
  readFileSync(`${dir}/${f}`, 'utf8').split('\n').forEach((line, i) => {
    if (!line.startsWith('- [')) return;
    const m = TASK.exec(line);
    if (!m) return bad.push(`${f}:${i + 1}: ${line.slice(0, 90)}`);
    const id = `${m[2]}-${m[3]}`;
    if (ids.has(id)) bad.push(`${f}:${i + 1}: duplicate ${id}`);
    ids.add(id);
    tasks.push({ file: f, done: m[1] === 'x', prefix: m[2], id, phase: m[4], pri: m[5], size: m[6], title: m[7] });
  });
}
const count = (pred) => tasks.filter(pred).length;
const prefixes = [...new Set(tasks.map((t) => t.prefix))];
const pct = (a, b) => (b ? `${Math.round((100 * a) / b)}%` : '—');

const PARKED = '09-parked.md';
const isParked = (t) => t.file === PARKED;
const live = tasks.filter((t) => !isParked(t));
const openLive = live.filter((t) => !t.done);
const byId = new Map(tasks.map((t) => [t.id, t]));
const prio = JSON.parse(readFileSync(`${dir}/priorities.json`, 'utf8'));
for (const tier of prio.tiers)
  for (const id of tier.ids) {
    const t = byId.get(id);
    if (!t) bad.push(`priorities.json: ${tier.name}: unknown task ${id}`);
    else if (isParked(t)) bad.push(`priorities.json: ${tier.name}: ${id} is parked`);
  }
const tiered = new Set(prio.tiers.flatMap((t) => t.ids));

let md = `# Suture & Steel — Master Roadmap

*The Malison Hours* · generated by \`node scripts/roadmap-index.mjs\` — do not edit by hand.

**${tasks.length} tasks** across ${prefixes.length} workstreams · **${count((t) => t.done)} done** (${pct(count((t) => t.done), tasks.length)}) ·
**${openLive.length} open** for the game now · **${count((t) => isParked(t) && !t.done)} parked** ([09-parked.md](roadmap/09-parked.md)).

## Scope
The game is **five chapters**. The goal now is **the whole game, playable end to end on Windows**: every chapter's
story, operations and Malison Hours, the other disciplines, and the look. Store, demo, marketing, localisation,
voice, playtest rounds and other-people work is parked until that exists. The phase tags on tasks (M0, Demo,
Alpha, Beta, Release, Post) record where each was first planned; the **priority tiers** below are the order of work.

## Priorities

Open tasks in order of work (\`docs/roadmap/priorities.json\`). Anything open and not in a tier is backlog.

`;
for (const tier of prio.tiers) {
  const open = tier.ids.map((id) => byId.get(id)).filter((t) => t && !t.done && !isParked(t));
  const done = tier.ids.filter((id) => byId.get(id)?.done).length;
  md += `### ${tier.name} — ${open.length} open, ${done} done\n\n${tier.why}\n\n`;
  for (const t of open) md += `- [ ] **${t.id}** (${t.size}) ${t.title}\n`;
  md += '\n';
}
const backlog = openLive.filter((t) => !tiered.has(t.id));
md += `### Backlog — ${backlog.length} open\n\nEngine, tooling, input, UI and accessibility work that isn't blocking the tiers above; see the workstream files.\n\n`;

md += `## Tasks by workstream and phase

| Workstream | ${PHASES.join(' | ')} | Total | Done | Open | Parked |
|---|${PHASES.map(() => '---:').join('|')}|---:|---:|---:|---:|
`;
for (const p of prefixes) {
  const row = PHASES.map((ph) => count((t) => t.prefix === p && t.phase === ph));
  md += `| \`${p}\` ${PREFIX_NAME[p] ?? ''} | ${row.join(' | ')} | ${count((t) => t.prefix === p)} | ${count((t) => t.prefix === p && t.done)} | ${count((t) => t.prefix === p && !t.done && !isParked(t))} | ${count((t) => t.prefix === p && !t.done && isParked(t))} |\n`;
}
const tot = PHASES.map((ph) => count((t) => t.phase === ph));
md += `| **All** | ${tot.map((n) => `**${n}**`).join(' | ')} | **${tasks.length}** | **${count((t) => t.done)}** | **${openLive.length}** | **${count((t) => isParked(t) && !t.done)}** |\n\n`;

md += `## Workstream documents\n\n`;
for (const f of files) md += `- [${f}](roadmap/${f}) — ${count((t) => t.file === f)} tasks\n`;
md += `- Research: [Trauma Center series](research/trauma-center.md) · [Warhammer Fantasy tone & IP-avoidance](research/warhammer-fantasy-tone.md)\n\n`;

md += `\n## Task format\n\n\`- [ ] PFX-0000 · Phase · Priority · Size · Title — acceptance criterion\` · Size S ≤ ½ day, M 1–3 days, L ≤ 2 weeks.\n`;

writeFileSync('docs/ROADMAP.md', md);
console.log(`${tasks.length} tasks, ${count((t) => t.done)} done; ${bad.length} malformed/duplicate lines`);
if (bad.length) console.log(bad.slice(0, 20).join('\n'));
