// Builds docs/ROADMAP.md from docs/roadmap/0*.md: validates task lines and tabulates progress.
// Usage: node scripts/roadmap-index.mjs
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';

const dir = 'docs/roadmap';
const files = readdirSync(dir).filter((f) => /^0\d-.*\.md$/.test(f)).sort();
const TASK = /^- \[([ x])\] ([A-Z]{3})-(\d{4}) · (M0|Demo|Alpha|Beta|Release|Post) · (P[0-3]) · ([SML]) · (.+)$/;
const PHASES = ['M0', 'Demo', 'Alpha', 'Beta', 'Release', 'Post'];
const PREFIX_NAME = {
  ENG: 'Engine & rendering', PLT: 'Platform, build & systems', INP: 'Input & controls', UIX: 'UI/UX, HUD & accessibility',
  AUD: 'Audio', QAT: 'QA, testing & tooling', LOC: 'Localisation', OPS: 'Production, legal & release',
  GAM: 'Core surgery gameplay', BOS: 'Malison bosses', NAR: 'Narrative & writing', CON: 'Content production', ART: 'Art & visual direction',
};
const tasks = [];
const bad = [];
const ids = new Set();
for (const f of files) {
  readFileSync(`${dir}/${f}`, 'utf8').split('\n').forEach((line, i) => {
    if (!line.startsWith('- [')) return;
    const m = TASK.exec(line);
    if (!m) return bad.push(`${f}:${i + 1}: ${line.slice(0, 90)}`);
    const id = `${m[2]}-${m[3]}`;
    if (ids.has(id)) bad.push(`${f}:${i + 1}: duplicate ${id}`);
    ids.add(id);
    tasks.push({ file: f, done: m[1] === 'x', prefix: m[2], id, phase: m[4], pri: m[5], size: m[6], title: m[7] });
  });
}
const count = (pred) => tasks.filter(pred).length;
const prefixes = [...new Set(tasks.map((t) => t.prefix))];
const pct = (a, b) => (b ? `${Math.round((100 * a) / b)}%` : '—');

let md = `# Suture & Steel — Master Roadmap

*The Malison Hours* · generated by \`node scripts/roadmap-index.mjs\` — do not edit by hand.

**${tasks.length} tasks** across ${prefixes.length} workstreams · **${count((t) => t.done)} done** (${pct(count((t) => t.done), tasks.length)}).

## Scope
The full game is **five chapters**. The first shipping target is a **release-quality Steam demo of Chapters I–II**
(10 operations, the Matins and Lauds Malisons), then Chapters III–V through Alpha, Beta and 1.0.

| Milestone | Definition of done |
|---|---|
| **M0 Prototype** | Engine, surgery simulation, vertical slice. |
| **Demo** | Chapters I–II at release quality on Steam as a free demo (Next Fest-ready): final art/audio for Ch I–II, options, tutorials, saves, controller/Steam Deck basics, wishlist flow. |
| **Alpha** | Every system feature-complete; Chapters III–V playable end-to-end with placeholder assets. |
| **Beta** | Content complete, final art/audio/VO, balancing, localisation, platform integration, broad testing. |
| **Release (1.0)** | Polish, performance, certification/store compliance, launch. |
| **Post** | Patches, free updates, DLC, community and mod tools. |

## Tasks by workstream and phase

| Workstream | ${PHASES.join(' | ')} | Total | Done |
|---|${PHASES.map(() => '---:').join('|')}|---:|---:|
`;
for (const p of prefixes) {
  const row = PHASES.map((ph) => count((t) => t.prefix === p && t.phase === ph));
  md += `| \`${p}\` ${PREFIX_NAME[p] ?? ''} | ${row.join(' | ')} | ${count((t) => t.prefix === p)} | ${count((t) => t.prefix === p && t.done)} |\n`;
}
const tot = PHASES.map((ph) => count((t) => t.phase === ph));
md += `| **All** | ${tot.map((n) => `**${n}**`).join(' | ')} | **${tasks.length}** | **${count((t) => t.done)}** |\n\n`;

md += `## Priority mix (Demo phase)\n\n| P0 | P1 | P2 | P3 |\n|---:|---:|---:|---:|\n| ${['P0', 'P1', 'P2', 'P3'].map((p) => count((t) => t.phase === 'Demo' && t.pri === p)).join(' | ')} |\n\n`;

md += `## Workstream documents\n\n`;
for (const f of files) md += `- [${f}](roadmap/${f}) — ${count((t) => t.file === f)} tasks\n`;
md += `- Research: [Trauma Center series](research/trauma-center.md) · [Warhammer Fantasy tone & IP-avoidance](research/warhammer-fantasy-tone.md)\n\n`;

md += `## Demo critical path (open P0 tasks)\n\n`;
for (const t of tasks.filter((t) => t.phase === 'Demo' && t.pri === 'P0' && !t.done)) md += `- [ ] **${t.id}** (${t.size}) ${t.title}\n`;
md += `\n## Task format\n\n\`- [ ] PFX-0000 · Phase · Priority · Size · Title — acceptance criterion\` · Size S ≤ ½ day, M 1–3 days, L ≤ 2 weeks.\n`;

writeFileSync('docs/ROADMAP.md', md);
console.log(`${tasks.length} tasks, ${count((t) => t.done)} done; ${bad.length} malformed/duplicate lines`);
if (bad.length) console.log(bad.slice(0, 20).join('\n'));
