// GENERATED by scripts/build-assets.ts from assets/ — do not edit. Run `npm run assets`.
import type { AssetEntry } from './types';

export type AssetId =
  | 'fonts/atkinson-hyperlegible-latin-400-italic'
  | 'fonts/atkinson-hyperlegible-latin-400-normal'
  | 'fonts/cinzel-latin-600-normal'
  | 'fonts/cinzel-latin-ext-600-normal'
  | 'fonts/eb-garamond-latin-500-italic'
  | 'fonts/eb-garamond-latin-500-normal'
  | 'fonts/eb-garamond-latin-ext-500-italic'
  | 'fonts/eb-garamond-latin-ext-500-normal'
  | 'sprites/fx'
  | 'textures/linen-detail'
  | 'textures/skin-detail'
  | 'textures/suture-rope'
  | 'textures/wood-table';

export type BundleId = 'boot' | 'title' | 'story-common' | 'ops-common' | 'chapter1' | 'chapter2' | 'chapter3' | 'chapter4' | 'chapter5';

export const MANIFEST: Record<AssetId, AssetEntry> = {
  "fonts/atkinson-hyperlegible-latin-400-italic": {
    "type": "font",
    "url": "assets/fonts_atkinson-hyperlegible-latin-400-italic.bc8825fd43.woff2",
    "bytes": 18292,
    "bundle": "boot",
    "hash": "bc8825fd43",
    "font": {
      "family": "Atkinson Hyperlegible",
      "style": "italic",
      "weight": "400"
    },
    "status": "final"
  },
  "fonts/atkinson-hyperlegible-latin-400-normal": {
    "type": "font",
    "url": "assets/fonts_atkinson-hyperlegible-latin-400-normal.d64ba838ef.woff2",
    "bytes": 17208,
    "bundle": "boot",
    "hash": "d64ba838ef",
    "font": {
      "family": "Atkinson Hyperlegible",
      "style": "normal",
      "weight": "400"
    },
    "status": "final"
  },
  "fonts/cinzel-latin-600-normal": {
    "type": "font",
    "url": "assets/fonts_cinzel-latin-600-normal.61efc27ceb.woff2",
    "bytes": 15204,
    "bundle": "boot",
    "hash": "61efc27ceb",
    "font": {
      "family": "Cinzel",
      "style": "normal",
      "weight": "600",
      "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
    },
    "status": "final"
  },
  "fonts/cinzel-latin-ext-600-normal": {
    "type": "font",
    "url": "assets/fonts_cinzel-latin-ext-600-normal.a5779eb98b.woff2",
    "bytes": 8352,
    "bundle": "boot",
    "hash": "a5779eb98b",
    "font": {
      "family": "Cinzel",
      "style": "normal",
      "weight": "600",
      "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF"
    },
    "status": "final"
  },
  "fonts/eb-garamond-latin-500-italic": {
    "type": "font",
    "url": "assets/fonts_eb-garamond-latin-500-italic.b2698d7de0.woff2",
    "bytes": 26952,
    "bundle": "boot",
    "hash": "b2698d7de0",
    "font": {
      "family": "EB Garamond",
      "style": "italic",
      "weight": "500",
      "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
    },
    "status": "final"
  },
  "fonts/eb-garamond-latin-500-normal": {
    "type": "font",
    "url": "assets/fonts_eb-garamond-latin-500-normal.7b252686ba.woff2",
    "bytes": 25264,
    "bundle": "boot",
    "hash": "7b252686ba",
    "font": {
      "family": "EB Garamond",
      "style": "normal",
      "weight": "500",
      "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
    },
    "status": "final"
  },
  "fonts/eb-garamond-latin-ext-500-italic": {
    "type": "font",
    "url": "assets/fonts_eb-garamond-latin-ext-500-italic.5bf2d44c78.woff2",
    "bytes": 49256,
    "bundle": "boot",
    "hash": "5bf2d44c78",
    "font": {
      "family": "EB Garamond",
      "style": "italic",
      "weight": "500",
      "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF"
    },
    "status": "final"
  },
  "fonts/eb-garamond-latin-ext-500-normal": {
    "type": "font",
    "url": "assets/fonts_eb-garamond-latin-ext-500-normal.6ba629125d.woff2",
    "bytes": 64076,
    "bundle": "boot",
    "hash": "6ba629125d",
    "font": {
      "family": "EB Garamond",
      "style": "normal",
      "weight": "500",
      "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF"
    },
    "status": "final"
  },
  "sprites/fx": {
    "type": "sheet",
    "url": "assets/sprites_fx.8cbf769be1.json",
    "bytes": 18853,
    "bundle": "ops-common",
    "hash": "8cbf769be1",
    "pages": [
      "assets/sprites_fx-0.12ffa0751d.png"
    ],
    "status": "final"
  },
  "textures/linen-detail": {
    "type": "image",
    "url": "assets/textures_linen-detail.babec6e2f2.jpg",
    "bytes": 49469,
    "bundle": "ops-common",
    "hash": "babec6e2f2",
    "status": "final"
  },
  "textures/skin-detail": {
    "type": "image",
    "url": "assets/textures_skin-detail.ae52a87522.jpg",
    "bytes": 78584,
    "bundle": "ops-common",
    "hash": "ae52a87522",
    "status": "final"
  },
  "textures/suture-rope": {
    "type": "image",
    "url": "assets/textures_suture-rope.a96472dc0c.jpg",
    "bytes": 21668,
    "bundle": "ops-common",
    "hash": "a96472dc0c",
    "status": "final"
  },
  "textures/wood-table": {
    "type": "image",
    "url": "assets/textures_wood-table.e48af6e2f2.jpg",
    "bytes": 55854,
    "bundle": "ops-common",
    "hash": "e48af6e2f2",
    "status": "final"
  }
};

export const BUNDLES: Record<BundleId, readonly AssetId[]> = {
  "boot": [
    "fonts/atkinson-hyperlegible-latin-400-italic",
    "fonts/atkinson-hyperlegible-latin-400-normal",
    "fonts/cinzel-latin-600-normal",
    "fonts/cinzel-latin-ext-600-normal",
    "fonts/eb-garamond-latin-500-italic",
    "fonts/eb-garamond-latin-500-normal",
    "fonts/eb-garamond-latin-ext-500-italic",
    "fonts/eb-garamond-latin-ext-500-normal"
  ],
  "title": [],
  "story-common": [],
  "ops-common": [
    "sprites/fx",
    "textures/linen-detail",
    "textures/skin-detail",
    "textures/suture-rope",
    "textures/wood-table"
  ],
  "chapter1": [],
  "chapter2": [],
  "chapter3": [],
  "chapter4": [],
  "chapter5": []
};

/** Sprite frame ids across every sheet. */
export const FRAME_IDS: readonly string[] = ["fx/drag-streak","fx/erase","fx/scorch","fx/soft-round","fx/splatter-1","fx/splatter-2","fx/splatter-3","fx/splatter-4","fx/stitch-mark"];
