// GENERATED by scripts/build-assets.ts from assets/ — do not edit. Run `npm run assets`.
import type { AssetEntry } from './types';

export type AssetId =
  | 'fonts/atkinson-hyperlegible-latin-400-italic'
  | 'fonts/atkinson-hyperlegible-latin-400-normal'
  | 'fonts/im-fell-english-latin-400-italic'
  | 'fonts/im-fell-english-latin-400-normal'
  | 'fonts/unifrakturmaguntia-latin-400-normal'
  | 'sprites/fx';

export type BundleId = 'boot' | 'title' | 'story-common' | 'ops-common' | 'chapter1' | 'chapter2';

export const MANIFEST: Record<AssetId, AssetEntry> = {
  "fonts/atkinson-hyperlegible-latin-400-italic": {
    "type": "font",
    "url": "assets/fonts_atkinson-hyperlegible-latin-400-italic.bc8825fd43.woff2",
    "bytes": 18292,
    "bundle": "boot",
    "hash": "bc8825fd43",
    "font": {
      "family": "Atkinson Hyperlegible",
      "style": "italic",
      "weight": "400"
    }
  },
  "fonts/atkinson-hyperlegible-latin-400-normal": {
    "type": "font",
    "url": "assets/fonts_atkinson-hyperlegible-latin-400-normal.d64ba838ef.woff2",
    "bytes": 17208,
    "bundle": "boot",
    "hash": "d64ba838ef",
    "font": {
      "family": "Atkinson Hyperlegible",
      "style": "normal",
      "weight": "400"
    }
  },
  "fonts/im-fell-english-latin-400-italic": {
    "type": "font",
    "url": "assets/fonts_im-fell-english-latin-400-italic.8fc678575e.woff2",
    "bytes": 57808,
    "bundle": "boot",
    "hash": "8fc678575e",
    "font": {
      "family": "IM Fell English",
      "style": "italic",
      "weight": "400"
    }
  },
  "fonts/im-fell-english-latin-400-normal": {
    "type": "font",
    "url": "assets/fonts_im-fell-english-latin-400-normal.248300df16.woff2",
    "bytes": 59880,
    "bundle": "boot",
    "hash": "248300df16",
    "font": {
      "family": "IM Fell English",
      "style": "normal",
      "weight": "400"
    }
  },
  "fonts/unifrakturmaguntia-latin-400-normal": {
    "type": "font",
    "url": "assets/fonts_unifrakturmaguntia-latin-400-normal.a467466874.woff2",
    "bytes": 26512,
    "bundle": "boot",
    "hash": "a467466874",
    "font": {
      "family": "UnifrakturMaguntia",
      "style": "normal",
      "weight": "400"
    }
  },
  "sprites/fx": {
    "type": "sheet",
    "url": "assets/sprites_fx.b1133c6138.json",
    "bytes": 21484,
    "bundle": "ops-common",
    "hash": "b1133c6138",
    "pages": [
      "assets/sprites_fx-0.353e239b33.png"
    ]
  }
};

export const BUNDLES: Record<BundleId, readonly AssetId[]> = {
  "boot": [
    "fonts/atkinson-hyperlegible-latin-400-italic",
    "fonts/atkinson-hyperlegible-latin-400-normal",
    "fonts/im-fell-english-latin-400-italic",
    "fonts/im-fell-english-latin-400-normal",
    "fonts/unifrakturmaguntia-latin-400-normal"
  ],
  "title": [],
  "story-common": [],
  "ops-common": [
    "sprites/fx"
  ],
  "chapter1": [],
  "chapter2": []
};

/** Sprite frame ids across every sheet. */
export const FRAME_IDS: readonly string[] = ["fx/drag-streak","fx/erase","fx/scorch","fx/soft-round","fx/splatter-1","fx/splatter-2","fx/splatter-3","fx/splatter-4","fx/stitch-mark"];
